name: Terraform Apply

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:
  terraform-apply:
    name: Apply Terraform
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: ðŸ“¦ Checkout Repository
        uses: actions/checkout@v3

      - name: ðŸ” Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ðŸ› ï¸ Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: âš™ï¸ Check and Run Terraform BootStrap Script
        run: |
          BUCKET_NAME="my-terraform-remote-state-bucket-aakash0912"
          TABLE_NAME="terraform-locks"
          REGION="us-east-1"
      
          bucket_exists=$(aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null && echo true || echo false)
          table_exists=$(aws dynamodb describe-table --table-name "$TABLE_NAME" --region "$REGION" 2>/dev/null && echo true || echo false)
      
          if [ "$bucket_exists" = false ] || [ "$table_exists" = false ]; then
            echo "S3 bucket or DynamoDB table missing. Running bootstrap..."
            chmod +x ./scripts/terraform_deploy_bootstrap.sh
            ./scripts/terraform_deploy_bootstrap.sh ${{ github.ref_name }}
          else
            echo "S3 bucket and DynamoDB table already exist. Skipping bootstrap."
          fi

      # - name: ðŸš€ Run Terraform BootStrap Script
      #   run: |
      #     chmod +x ./scripts/terraform_deploy_bootstrap.sh
      #     ./scripts/terraform_deploy_bootstrap.sh ${{ github.ref_name }}

      - name: ðŸš€ Run Terraform Main Script
        run: |
          chmod +x ./scripts/terraform_deploy_main.sh
          ./scripts/terraform_deploy_main.sh ${{ github.ref_name }}
